plugins {
    id 'com.android.application'
}

android {
    namespace 'com.carsocx.igovosk'
    compileSdk 35

    defaultConfig {
        applicationId 'com.carsocx.igovosk'
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName '0.1-test'

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
    implementation 'com.google.code.gson:gson:2.11.0'
}
